[program:conduitvpn]
environment=HOME="/root",USER="root",LC_ALL="C.UTF-8",LANG="C.UTF-8",NETWORK_MODE="container",UI_HOST="0.0.0.0",LOCAL_PROXY_HOST="0.0.0.0",CONDUIT_DATA_DIR="/data/conduitvpn"
process_name=conduitvpn
priority=1                       ;最先启动: 住宅IP出口, 其余进程依赖它
command=/usr/bin/conduitvpn
directory=/data/conduitvpn
numprocs=1
stopsignal=INT
autostart=true
autorestart=true
killasgroup=true
stopasgroup=true
startsecs=5
startretries=10000
redirect_stderr=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stdout
stdout_logfile_maxbytes=0
